<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KecamatanSeeder extends Seeder
{
    public function run()
    {
        $kecamatanList = [
            // Lampung Selatan (kabupaten_id = 1)
            ['nama' => 'Bakauheni', 'kabupaten_id' => 1],
            ['nama' => 'Candipuro', 'kabupaten_id' => 1],
            ['nama' => 'Jati Agung', 'kabupaten_id' => 1],
            ['nama' => 'Kalianda', 'kabupaten_id' => 1],
            ['nama' => 'Katibung', 'kabupaten_id' => 1],
            ['nama' => 'Ketapang', 'kabupaten_id' => 1],
            ['nama' => 'Merbau Mataram', 'kabupaten_id' => 1],
            ['nama' => 'Natar', 'kabupaten_id' => 1],
            ['nama' => 'Palas', 'kabupaten_id' => 1],
            ['nama' => 'Penengahan', 'kabupaten_id' => 1],
            ['nama' => 'Rajabasa', 'kabupaten_id' => 1],
            ['nama' => 'Sidomulyo', 'kabupaten_id' => 1],
            ['nama' => 'Sragi', 'kabupaten_id' => 1],
            ['nama' => 'Tanjung Bintang', 'kabupaten_id' => 1],
            ['nama' => 'Tanjung Sari', 'kabupaten_id' => 1],
            ['nama' => 'Way Panji', 'kabupaten_id' => 1],
            ['nama' => 'Way Sulan', 'kabupaten_id' => 1],

            // Lampung Barat (kabupaten_id = 2)
            ['nama' => 'Balik Bukit', 'kabupaten_id' => 2],
            ['nama' => 'Bandar Negeri Suoh', 'kabupaten_id' => 2],
            ['nama' => 'Batu Brak', 'kabupaten_id' => 2],
            ['nama' => 'Batu Ketulis', 'kabupaten_id' => 2],
            ['nama' => 'Belalau', 'kabupaten_id' => 2],
            ['nama' => 'Gedung Surian', 'kabupaten_id' => 2],
            ['nama' => 'Kebun Tebu', 'kabupaten_id' => 2],
            ['nama' => 'Lumbok Seminung', 'kabupaten_id' => 2],
            ['nama' => 'Pagar Dewa', 'kabupaten_id' => 2],
            ['nama' => 'Sekincau', 'kabupaten_id' => 2],
            ['nama' => 'Sukau', 'kabupaten_id' => 2],
            ['nama' => 'Sumber Jaya', 'kabupaten_id' => 2],
            ['nama' => 'Suoh', 'kabupaten_id' => 2],
            ['nama' => 'Way Tenong', 'kabupaten_id' => 2],
            ['nama' => 'Air Hitam', 'kabupaten_id' => 2],

            // Lampung Tengah (kabupaten_id = 3)
            ['nama' => 'Gunung Sugih', 'kabupaten_id' => 3],
            ['nama' => 'Terbanggi Besar', 'kabupaten_id' => 3],
            ['nama' => 'Seputih Banyak', 'kabupaten_id' => 3],
            ['nama' => 'Seputih Raman', 'kabupaten_id' => 3],
            ['nama' => 'Seputih Surabaya', 'kabupaten_id' => 3],
            ['nama' => 'Terusan Nunyai', 'kabupaten_id' => 3],
            ['nama' => 'Trimurjo', 'kabupaten_id' => 3],
            ['nama' => 'Bangun Rejo', 'kabupaten_id' => 3],
            ['nama' => 'Padang Ratu', 'kabupaten_id' => 3],
            ['nama' => 'Bekri', 'kabupaten_id' => 3],
            ['nama' => 'Bumi Ratu Nuban', 'kabupaten_id' => 3],
            ['nama' => 'Bandar Mataram', 'kabupaten_id' => 3],
            ['nama' => 'Bandar Surabaya', 'kabupaten_id' => 3],
            ['nama' => 'Bumi Nabung', 'kabupaten_id' => 3],
            ['nama' => 'Way Pengubuan', 'kabupaten_id' => 3],
            ['nama' => 'Pubian', 'kabupaten_id' => 3],
            ['nama' => 'Selagai Lingga', 'kabupaten_id' => 3],
            ['nama' => 'Anak Tuha', 'kabupaten_id' => 3],
            ['nama' => 'Sendang Agung', 'kabupaten_id' => 3],
            ['nama' => 'Kota Gajah', 'kabupaten_id' => 3],
            ['nama' => 'Way Seputih', 'kabupaten_id' => 3],
            ['nama' => 'Seputih Agung', 'kabupaten_id' => 3],

            // Lampung Timur (kabupaten_id = 4)
            ['nama' => 'Bandar Sribawono', 'kabupaten_id' => 4],
            ['nama' => 'Batang Hari', 'kabupaten_id' => 4],
            ['nama' => 'Batang Hari Nuban', 'kabupaten_id' => 4],
            ['nama' => 'Braja Selebah', 'kabupaten_id' => 4],
            ['nama' => 'Bumi Agung', 'kabupaten_id' => 4],
            ['nama' => 'Gunung Pelindung', 'kabupaten_id' => 4],
            ['nama' => 'Jabung', 'kabupaten_id' => 4],
            ['nama' => 'Labuhan Maringgai', 'kabupaten_id' => 4],
            ['nama' => 'Labuhan Ratu', 'kabupaten_id' => 4],
            ['nama' => 'Marga Sekampung', 'kabupaten_id' => 4],
            ['nama' => 'Marga Tiga', 'kabupaten_id' => 4],
            ['nama' => 'Mataram Baru', 'kabupaten_id' => 4],
            ['nama' => 'Melinting', 'kabupaten_id' => 4],
            ['nama' => 'Metro Kibang', 'kabupaten_id' => 4],
            ['nama' => 'Pasir Sakti', 'kabupaten_id' => 4],
            ['nama' => 'Pekalongan', 'kabupaten_id' => 4],
            ['nama' => 'Purbolinggo', 'kabupaten_id' => 4],
            ['nama' => 'Raman Utara', 'kabupaten_id' => 4],
            ['nama' => 'Sekampung', 'kabupaten_id' => 4],
            ['nama' => 'Sekampung Udik', 'kabupaten_id' => 4],
            ['nama' => 'Sukadana', 'kabupaten_id' => 4],
            ['nama' => 'Waway Karya', 'kabupaten_id' => 4],
            ['nama' => 'Way Bungur', 'kabupaten_id' => 4],
            ['nama' => 'Way Jepara', 'kabupaten_id' => 4],

            // Mesuji (kabupaten_id = 5)
            ['nama' => 'Mesuji', 'kabupaten_id' => 5],
            ['nama' => 'Mesuji Timur', 'kabupaten_id' => 5],
            ['nama' => 'Rawa Jitu Utara', 'kabupaten_id' => 5],
            ['nama' => 'Simpang Pematang', 'kabupaten_id' => 5],
            ['nama' => 'Panca Jaya', 'kabupaten_id' => 5],
            ['nama' => 'Tanjung Raya', 'kabupaten_id' => 5],
            ['nama' => 'Way Serdang', 'kabupaten_id' => 5],

            // Pringsewu (kabupaten_id = 6)
            ['nama' => 'Pringsewu', 'kabupaten_id' => 6],
            ['nama' => 'Ambarawa', 'kabupaten_id' => 6],
            ['nama' => 'Pardasuka', 'kabupaten_id' => 6],
            ['nama' => 'Gading Rejo', 'kabupaten_id' => 6],
            ['nama' => 'Adi Luwih', 'kabupaten_id' => 6],
            ['nama' => 'Pagelaran', 'kabupaten_id' => 6],
            ['nama' => 'Pagelaran Utara', 'kabupaten_id' => 6],
            ['nama' => 'Sukoharjo', 'kabupaten_id' => 6],
            ['nama' => 'Banyumas', 'kabupaten_id' => 6],

            // Pesisir Barat (kabupaten_id = 7)
            ['nama' => 'Pesisir Tengah', 'kabupaten_id' => 7],
            ['nama' => 'Pesisir Selatan', 'kabupaten_id' => 7],
            ['nama' => 'Pesisir Utara', 'kabupaten_id' => 7],
            ['nama' => 'Krui Selatan', 'kabupaten_id' => 7],
            ['nama' => 'Way Krui', 'kabupaten_id' => 7],
            ['nama' => 'Karya Penggawa', 'kabupaten_id' => 7],
            ['nama' => 'Pulau Pisang', 'kabupaten_id' => 7],
            ['nama' => 'Lemong', 'kabupaten_id' => 7],
            ['nama' => 'Ngaras', 'kabupaten_id' => 7],
            ['nama' => 'Bengkunat', 'kabupaten_id' => 7],
            ['nama' => 'Ngambur', 'kabupaten_id' => 7],

            // Tanggamus (kabupaten_id = 8)
            ['nama' => 'Talang Padang', 'kabupaten_id' => 8],
            ['nama' => 'Gisting', 'kabupaten_id' => 8],
            ['nama' => 'Gunung Alip', 'kabupaten_id' => 8],
            ['nama' => 'Sumberejo', 'kabupaten_id' => 8],
            ['nama' => 'Wonosobo', 'kabupaten_id' => 8],
            ['nama' => 'Semaka', 'kabupaten_id' => 8],
            ['nama' => 'Pugung', 'kabupaten_id' => 8],
            ['nama' => 'Pulau Panggung', 'kabupaten_id' => 8],
            ['nama' => 'Ulu Belu', 'kabupaten_id' => 8],
            ['nama' => 'Cukuh Balak', 'kabupaten_id' => 8],
            ['nama' => 'Kelumbayan', 'kabupaten_id' => 8],
            ['nama' => 'Kelumbayan Barat', 'kabupaten_id' => 8],
            ['nama' => 'Limau', 'kabupaten_id' => 8],
            ['nama' => 'Pematang Sawa', 'kabupaten_id' => 8],
            ['nama' => 'Bandar Negeri Semuong', 'kabupaten_id' => 8],
            ['nama' => 'Air Naningan', 'kabupaten_id' => 8],
            ['nama' => 'Bulok', 'kabupaten_id' => 8],
            ['nama' => 'Kota Agung Pusat', 'kabupaten_id' => 8],
            ['nama' => 'Kota Agung Timur', 'kabupaten_id' => 8],
            ['nama' => 'Kota Agung Barat', 'kabupaten_id' => 8],

            // Tulang Bawang (kabupaten_id = 9)
            ['nama' => 'Banjar Agung', 'kabupaten_id' => 9],
            ['nama' => 'Banjar Baru', 'kabupaten_id' => 9],
            ['nama' => 'Banjar Margo', 'kabupaten_id' => 9],
            ['nama' => 'Menggala', 'kabupaten_id' => 9],
            ['nama' => 'Menggala Timur', 'kabupaten_id' => 9],
            ['nama' => 'Gedung Aji', 'kabupaten_id' => 9],
            ['nama' => 'Gedung Aji Baru', 'kabupaten_id' => 9],
            ['nama' => 'Gedung Meneng', 'kabupaten_id' => 9],
            ['nama' => 'Dente Teladas', 'kabupaten_id' => 9],
            ['nama' => 'Meraksa Aji', 'kabupaten_id' => 9],
            ['nama' => 'Penawar Aji', 'kabupaten_id' => 9],
            ['nama' => 'Penawar Tama', 'kabupaten_id' => 9],
            ['nama' => 'Rawapitu', 'kabupaten_id' => 9],
            ['nama' => 'Rawajitu Selatan', 'kabupaten_id' => 9],
            ['nama' => 'Rawajitu Timur', 'kabupaten_id' => 9],
            ['nama' => 'Rawajitu Utara', 'kabupaten_id' => 9],

            // Tulang Bawang Barat (kabupaten_id = 10)
            ['nama' => 'Tulang Bawang Tengah', 'kabupaten_id' => 10],
            ['nama' => 'Tumijajar', 'kabupaten_id' => 10],
            ['nama' => 'Tulang Bawang Udik', 'kabupaten_id' => 10],
            ['nama' => 'Gunung Terang', 'kabupaten_id' => 10],
            ['nama' => 'Gunung Agung', 'kabupaten_id' => 10],
            ['nama' => 'Way Kenanga', 'kabupaten_id' => 10],
            ['nama' => 'Lambu Kibang', 'kabupaten_id' => 10],
            ['nama' => 'Batu Putih', 'kabupaten_id' => 10],
            ['nama' => 'Pagar Dewa', 'kabupaten_id' => 10],

            // Way Kanan (kabupaten_id = 11)
            ['nama' => 'Baradatu', 'kabupaten_id' => 11],
            ['nama' => 'Blambangan Umpu', 'kabupaten_id' => 11],
            ['nama' => 'Bahuga', 'kabupaten_id' => 11],
            ['nama' => 'Banjit', 'kabupaten_id' => 11],
            ['nama' => 'Kasui', 'kabupaten_id' => 11],
            ['nama' => 'Bumi Agung', 'kabupaten_id' => 11],
            ['nama' => 'Buay Bahuga', 'kabupaten_id' => 11],
            ['nama' => 'Negeri Agung', 'kabupaten_id' => 11],
            ['nama' => 'Negara Batin', 'kabupaten_id' => 11],
            ['nama' => 'Negeri Besar', 'kabupaten_id' => 11],
            ['nama' => 'Pakuan Ratu', 'kabupaten_id' => 11],
            ['nama' => 'Rebang Tangkas', 'kabupaten_id' => 11],
            ['nama' => 'Way Tuba', 'kabupaten_id' => 11],
            ['nama' => 'Gunung Labuhan', 'kabupaten_id' => 11],

            // Bandar Lampung (kabupaten_id = 12)
            ['nama' => 'Bumi Waras', 'kabupaten_id' => 12],
            ['nama' => 'Enggal', 'kabupaten_id' => 12],
            ['nama' => 'Kedamaian', 'kabupaten_id' => 12],
            ['nama' => 'Kedaton', 'kabupaten_id' => 12],
            ['nama' => 'Kemiling', 'kabupaten_id' => 12],
            ['nama' => 'Labuhan Ratu', 'kabupaten_id' => 12],
            ['nama' => 'Langkapura', 'kabupaten_id' => 12],
            ['nama' => 'Panjang', 'kabupaten_id' => 12],
            ['nama' => 'Rajabasa', 'kabupaten_id' => 12],
            ['nama' => 'Sukabumi', 'kabupaten_id' => 12],
            ['nama' => 'Sukarame', 'kabupaten_id' => 12],
            ['nama' => 'Tanjungkarang Barat', 'kabupaten_id' => 12],
            ['nama' => 'Tanjungkarang Pusat', 'kabupaten_id' => 12],
            ['nama' => 'Tanjungkarang Timur', 'kabupaten_id' => 12],
            ['nama' => 'Telukbetung Barat', 'kabupaten_id' => 12],
            ['nama' => 'Telukbetung Selatan', 'kabupaten_id' => 12],
            ['nama' => 'Telukbetung Timur', 'kabupaten_id' => 12],
            ['nama' => 'Telukbetung Utara', 'kabupaten_id' => 12],
            ['nama' => 'Way Halim', 'kabupaten_id' => 12],
            ['nama' => 'Tanjung Senang', 'kabupaten_id' => 12],

            // Metro (kabupaten_id = 13)
            ['nama' => 'Metro Pusat', 'kabupaten_id' => 13],
            ['nama' => 'Metro Timur', 'kabupaten_id' => 13],
            ['nama' => 'Metro Barat', 'kabupaten_id' => 13],
            ['nama' => 'Metro Utara', 'kabupaten_id' => 13],
            ['nama' => 'Metro Selatan', 'kabupaten_id' => 13],


            // Pesawaran (kabupaten_id = 14)
            ['nama' => 'Gedong Tataan', 'kabupaten_id' => 14],
            ['nama' => 'Negeri Katon', 'kabupaten_id' => 14],
            ['nama' => 'Tegineneng', 'kabupaten_id' => 14],
            ['nama' => 'Way Lima', 'kabupaten_id' => 14],
            ['nama' => 'Padang Cermin', 'kabupaten_id' => 14],
            ['nama' => 'Teluk Pandan', 'kabupaten_id' => 14],
            ['nama' => 'Way Khilau', 'kabupaten_id' => 14],
            ['nama' => 'Marga Punduh', 'kabupaten_id' => 14],
            ['nama' => 'Punduh Pidada', 'kabupaten_id' => 14],
            ['nama' => 'Kedondong', 'kabupaten_id' => 14],
            ['nama' => 'Way Ratai', 'kabupaten_id' => 14],

            // Lampung Utara (kabupaten_id = 15)
            ['nama' => 'Abung Barat', 'kabupaten_id' => 15],
            ['nama' => 'Abung Kunang', 'kabupaten_id' => 15],
            ['nama' => 'Abung Pekurun', 'kabupaten_id' => 15],
            ['nama' => 'Abung Selatan', 'kabupaten_id' => 15],
            ['nama' => 'Abung Semuli', 'kabupaten_id' => 15],
            ['nama' => 'Abung Surakarta', 'kabupaten_id' => 15],
            ['nama' => 'Abung Tengah', 'kabupaten_id' => 15],
            ['nama' => 'Abung Timur', 'kabupaten_id' => 15],
            ['nama' => 'Abung Tinggi', 'kabupaten_id' => 15],
            ['nama' => 'Blambangan Pagar', 'kabupaten_id' => 15],
            ['nama' => 'Bukit Kemuning', 'kabupaten_id' => 15],
            ['nama' => 'Bunga Mayang', 'kabupaten_id' => 15],
            ['nama' => 'Hulu Sungkai', 'kabupaten_id' => 15],
            ['nama' => 'Kotabumi', 'kabupaten_id' => 15],
            ['nama' => 'Kotabumi Selatan', 'kabupaten_id' => 15],
            ['nama' => 'Kotabumi Utara', 'kabupaten_id' => 15],
            ['nama' => 'Muara Sungkai', 'kabupaten_id' => 15],
            ['nama' => 'Sungkai Barat', 'kabupaten_id' => 15],
            ['nama' => 'Sungkai Jaya', 'kabupaten_id' => 15],
            ['nama' => 'Sungkai Selatan', 'kabupaten_id' => 15],
            ['nama' => 'Sungkai Tengah', 'kabupaten_id' => 15],
            ['nama' => 'Sungkai Utara', 'kabupaten_id' => 15],
            ['nama' => 'Tanjung Raja', 'kabupaten_id' => 15],
        ];

        foreach ($kecamatanList as $kec) {
            \App\Models\Kecamatan::create($kec);
        }
    }

}
